// Security + business-rule regression suite for migrations 018-021 (run: pnpm test:db).
import { createDb, session } from './harness.mjs'
for (const ev of ['uncaughtException', 'unhandledRejection']) process.on(ev, (e) => { console.error('FATAL:', String(e?.message ?? e).slice(0, 400)); process.exit(2) })
import { seed, ID, slotId, fillCart } from './seed.mjs'

const { db } = await createDb()
await seed(db)
const s = session(db)
let pass = 0, fail = 0
const log = (ok, name, extra = '') => { ok ? pass++ : fail++; console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${ok ? '' : '  <-- ' + extra}`) }
const rejects = async (name, p, re) => {
  try { await p; log(false, name, 'expected an error, statement succeeded') }
  catch (e) { const m = String(e.message); log(!re || re.test(m), name, m.slice(0, 160)) }
}
const eq = (name, a, b) => log(JSON.stringify(a) === JSON.stringify(b), name, `got ${JSON.stringify(a)} want ${JSON.stringify(b)}`)
const one = async (sql, p) => (await db.query(sql, p)).rows[0]
const inv = async (food) => (await one(`select quantity_available q from inventory where food_item_id=$1`, [food])).q
const booked = async (slot) => (await one(`select booked_count b from pickup_slots where id=$1`, [slot])).b

const slotA = await slotId(db, ID.outletA, 1)
const slotA2 = await slotId(db, ID.outletA, 2)
const slotB = await slotId(db, ID.outletB, 1)
const slotPast = await slotId(db, ID.outletA, -1)
const slotFar = await slotId(db, ID.outletA, 30)

console.log('\n== Identity / profiles')
await rejects('student cannot self-promote to ADMIN', s.as(ID.student, `update profiles set role='ADMIN' where id=$1`, [ID.student]), /cannot change your own role/)
await rejects('student cannot self-promote to VENDOR', s.as(ID.student, `update profiles set role='VENDOR' where id=$1`, [ID.student]), /cannot change your own role/)
await rejects('student cannot re-activate / change email', s.as(ID.student, `update profiles set email='x@y.z' where id=$1`, [ID.student]), /cannot change/)
await s.as(ID.student, `update profiles set name='Stu Renamed', phone='999' where id=$1`, [ID.student]); log(true, 'student can still edit name/phone')
eq('student sees only own profile', (await s.as(ID.student, `select id from profiles`)).rows.map(r => r.id), [ID.student])
await rejects('new profile cannot be created as ADMIN', s.as('99999999-9999-9999-9999-999999999999', `insert into profiles(id,name,email,role) values ('99999999-9999-9999-9999-999999999999','x','x@x','ADMIN')`))
eq('vendor sees only self before any orders', (await s.as(ID.vendor, `select id from profiles`)).rows.map(r => r.id).sort(), [ID.vendor])
await rejects('admin cannot change own role', s.as(ID.admin, `select admin_set_user_role($1,'STUDENT')`, [ID.admin]), /own role/)
await rejects('student cannot call admin_set_user_role', s.as(ID.student, `select admin_set_user_role($1,'ADMIN')`, [ID.student]), /ADMIN/)
await s.as(ID.admin, `select admin_set_user_role($1,'VENDOR')`, [ID.pending]); eq('admin approves pending vendor', (await one(`select role::text r from profiles where id=$1`, [ID.pending])).r, 'VENDOR')
await db.query(`update profiles set role='PENDING_VENDOR' where id=$1`, [ID.pending])

console.log('\n== Function grants')
await rejects('anon cannot execute mark_payment_verified', s.anon(`select mark_payment_verified($1,'x','x','PAID')`, [ID.student]), /permission denied/)
await rejects('student cannot execute mark_payment_verified', s.as(ID.student, `select mark_payment_verified($1,'x','x','PAID')`, [ID.student]), /permission denied/)
await rejects('student cannot execute crave_payment_apply', s.as(ID.student, `select crave_payment_apply('order_x','pay_x','PAID')`), /permission denied/)
await rejects('anon cannot execute place_order', s.anon(`select place_order($1,$1,'ONLINE')`, [ID.student]), /permission denied/)
await rejects('anon cannot execute get_management_dashboard', s.anon(`select get_management_dashboard()`), /permission denied/)
await rejects('student cannot read management dashboard', s.as(ID.student, `select get_management_dashboard()`), /ADMIN/)
await rejects('vendor cannot read management dashboard', s.as(ID.vendor, `select get_management_dashboard()`), /ADMIN/)
await rejects('student cannot expire orders directly', s.as(ID.student, `select crave_expire_unpaid_orders()`), /permission denied/)

console.log('\n== Cart -> order (server authoritative)')
let cart = await fillCart(s, ID.student, ID.outletA, [{ food: ID.food, qty: 2, price: 1 }, { food: ID.food2, qty: 1, price: 1, opts: [{ variant: ID.var1, option: ID.opt1 }], note: 'less spicy' }])
const i0 = await inv(ID.food), b0 = await booked(slotA)
const o1 = (await s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER') id`, [cart, slotA])).rows[0].id
const ord = await one(`select subtotal::float s, tax::float t, total::float tot, status::text st, payment_status::text ps, user_id from orders where id=$1`, [o1])
eq('server computes price (2*100 + (50+20) = 270, tax 5%)', [ord.s, ord.t, ord.tot], [270, 13.5, 283.5])
eq('client price=1 ignored; initial state', [ord.st, ord.ps], ['PLACED', 'PENDING'])
eq('inventory decremented', await inv(ID.food), i0 - 2)
eq('slot booked_count +1', await booked(slotA), b0 + 1)
eq('cart emptied after order', (await one(`select count(*)::int c from cart_items where cart_id=$1`, [cart])).c, 0)
eq('special instructions copied to order item', (await one(`select special_instructions n from order_items where order_id=$1 and food_name='Dosa'`, [o1])).n, 'less spicy')
await rejects('double submit of the same cart fails', s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER')`, [cart, slotA]), /Cart is empty/)
const tok = await s.as(ID.student, `select token_value from pickup_tokens where order_id=$1`, [o1]); eq('student can read their own pickup token', tok.rows.length, 1)
eq('vendor of outlet sees the counter order', (await s.as(ID.vendor, `select id from orders`)).rows.length, 1)
eq('other vendor sees nothing', (await s.as(ID.vendor2, `select id from orders`)).rows.length, 0)
eq('other student sees nothing', (await s.as(ID.student2, `select id from orders`)).rows.length, 0)
eq('vendor can now see the customer profile (and only that)', (await s.as(ID.vendor, `select id from profiles order by id`)).rows.map(r => r.id).sort(), [ID.student, ID.vendor].sort())

console.log('\n== Validation inside place_order')
cart = await fillCart(s, ID.student, ID.outletA, [{ food: ID.food2, qty: 1 }])
await rejects('required variant missing', s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER')`, [cart, slotA]), /Please choose "Size"/)
cart = await fillCart(s, ID.student, ID.outletA, [{ food: ID.food, qty: 1, opts: [{ variant: ID.var1, option: ID.opt1 }] }])
await rejects('customization from another food rejected', s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER')`, [cart, slotA]), /Invalid customization/)
cart = await fillCart(s, ID.student, ID.outletA, [{ food: ID.food, qty: 21 }]); await rejects('quantity > 20 rejected', s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER')`, [cart, slotA]), /Invalid quantity/)
cart = await fillCart(s, ID.student, ID.outletA, [{ food: ID.food, qty: 1 }])
await rejects('slot of another outlet rejected', s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER')`, [cart, slotB]), /Pickup slot not found/)
await rejects('past-date slot rejected', s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER')`, [cart, slotPast]), /in the past/)
await rejects('slot > 7 days ahead rejected', s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER')`, [cart, slotFar]), /too far/)
const slotToday0 = (await one(`select id from pickup_slots where outlet_id=$1 and start_time='00:00'`, [ID.outletA])).id
await rejects('already-passed slot today rejected (IST)', s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER')`, [cart, slotToday0]), /already passed/)
await rejects('unknown payment method rejected', s.as(ID.student, `select place_order($1,$2,'BITCOIN')`, [cart, slotA]), /Unsupported/)
await rejects('vendor cannot place orders', s.as(ID.vendor, `select place_order($1,$2,'PAY_AT_COUNTER')`, [cart, slotA]), /student accounts/)
await db.query(`update outlets set is_active=false where id=$1`, [ID.outletA]); await rejects('inactive outlet rejected', s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER')`, [cart, slotA]), /not active/); await db.query(`update outlets set is_active=true where id=$1`, [ID.outletA])
await db.query(`update food_items set is_available=false where id=$1`, [ID.food]); await rejects('unavailable item rejected', s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER')`, [cart, slotA]), /unavailable/); await db.query(`update food_items set is_available=true where id=$1`, [ID.food])

console.log('\n== Overselling')
await db.query(`update inventory set quantity_available=1 where food_item_id=$1`, [ID.food])
cart = await fillCart(s, ID.student, ID.outletA, [{ food: ID.food, qty: 1 }, { food: ID.food, qty: 1, note: 'second row same food' }])
await rejects('same food on two cart lines cannot exceed stock (old code let this through)', s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER')`, [cart, slotA]), /Insufficient stock/)
eq('failed order left stock untouched (atomic rollback)', await inv(ID.food), 1)
cart = await fillCart(s, ID.student, ID.outletA, [{ food: ID.food, qty: 1 }])
const c2 = await fillCart(s, ID.student2, ID.outletA, [{ food: ID.food, qty: 1 }])
const oa = (await s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER') id`, [cart, slotA2])).rows[0].id
await rejects('second buyer of the last unit is refused', s.as(ID.student2, `select place_order($1,$2,'PAY_AT_COUNTER')`, [c2, slotA2]), /Insufficient stock/)
eq('stock is 0 not negative', await inv(ID.food), 0)
await s.as(ID.student, `select cancel_my_order($1)`, [oa]); eq('cancelling restores stock exactly once', await inv(ID.food), 1)
await rejects('cannot cancel twice', s.as(ID.student, `select cancel_my_order($1)`, [oa]), /Illegal order transition|not found/i)
eq('stock not double-restored', await inv(ID.food), 1)
await db.query(`update inventory set quantity_available=10`)

console.log('\n== Slot capacity')
await db.query(`update pickup_slots set capacity=1 where id=$1`, [slotA2])
cart = await fillCart(s, ID.student, ID.outletA, [{ food: ID.food, qty: 1 }]); const oc = (await s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER') id`, [cart, slotA2])).rows[0].id
eq('slot marked FULL at capacity', (await one(`select status::text s, booked_count b from pickup_slots where id=$1`, [slotA2])), { s: 'FULL', b: 1 })
const c3 = await fillCart(s, ID.student2, ID.outletA, [{ food: ID.food, qty: 1 }]); await rejects('full slot refuses a second booking', s.as(ID.student2, `select place_order($1,$2,'PAY_AT_COUNTER')`, [c3, slotA2]), /not available|full/i)
await s.as(ID.student, `select cancel_my_order($1)`, [oc]); eq('cancel frees the slot', (await one(`select status::text s, booked_count b from pickup_slots where id=$1`, [slotA2])), { s: 'AVAILABLE', b: 0 })

console.log('\n== Order tampering by the student')
await rejects('student cannot set payment_status=PAID', s.as(ID.student, `update orders set payment_status='PAID' where id=$1`, [o1]), /Protected order fields/)
await rejects('student cannot lower total', s.as(ID.student, `update orders set total=1 where id=$1`, [o1]), /Protected order fields/)
await rejects('student cannot jump to PICKED_UP', s.as(ID.student, `update orders set status='PICKED_UP' where id=$1`, [o1]), /Illegal order transition/)
await rejects('student cannot reassign order to another user', s.as(ID.student, `update orders set user_id=$2 where id=$1`, [o1, ID.student2]), /Protected order fields/)
await rejects('student cannot insert an order directly', s.as(ID.student, `insert into orders(order_number,user_id,vendor_id,outlet_id,subtotal,tax,total) values ('X',$1,$2,$3,0,0,0)`, [ID.student, ID.vendor, ID.outletA]), /permission denied/)
await rejects('student cannot insert payments', s.as(ID.student, `insert into payments(order_id,amount) values ($1,0)`, [o1]), /permission denied/)
await rejects('student cannot insert order_items', s.as(ID.student, `insert into order_items(order_id,food_item_id,food_name,quantity,unit_price,total_price,is_veg) values ($1,$2,'x',1,0,0,true)`, [o1, ID.food]), /permission denied/)
await rejects('student cannot edit catalogue price', s.as(ID.student, `update food_items set price=1 where id=$1`, [ID.food]).then(r => { if (!r.affectedRows) throw new Error('0 rows (RLS)'); }), /0 rows/)
await rejects('student cannot forge pickup token', s.as(ID.student, `update pickup_tokens set is_used=true where order_id=$1`, [o1]).then(r => { if (!r.affectedRows) throw new Error('0 rows (RLS)') }), /0 rows/)

console.log('\n== Vendor lifecycle + isolation')
await rejects('other vendor cannot accept this order', s.as(ID.vendor2, `select vendor_accept_order($1)`, [o1]), /Order not found/)
await rejects('vendor cannot skip ACCEPTED', s.as(ID.vendor, `select vendor_mark_ready($1)`, [o1]), /Illegal order transition/)
await rejects('vendor cannot change totals', s.as(ID.vendor, `update orders set total=0 where id=$1`, [o1]), /Protected order fields/)
await rejects('vendor cannot mark payment PAID directly', s.as(ID.vendor, `update orders set payment_status='PAID' where id=$1`, [o1]), /Protected order fields/)
await s.as(ID.vendor, `select vendor_accept_order($1)`, [o1]); await s.as(ID.vendor, `select vendor_start_preparing($1)`, [o1]); await s.as(ID.vendor, `select vendor_mark_ready($1)`, [o1])
await rejects('student cannot cancel once the vendor accepted', s.as(ID.student, `select cancel_my_order($1)`, [o1]), /Illegal order transition|not found/i)
const t = (await one(`select token_value v from pickup_tokens where order_id=$1`, [o1])).v
await rejects('vendor B cannot redeem vendor A token', s.as(ID.vendor2, `select verify_pickup_token($1)`, [t]), /Invalid pickup token/)
await rejects('student cannot redeem token', s.as(ID.student, `select verify_pickup_token($1)`, [t]), /Only vendors/)
await s.as(ID.vendor, `select verify_pickup_token($1)`, [t])
eq('token scan -> PICKED_UP, cash settled', (await one(`select o.status::text s, o.payment_status::text ps, p.status::text pps from orders o join payments p on p.order_id=o.id where o.id=$1`, [o1])), { s: 'PICKED_UP', ps: 'PAID', pps: 'PAID' })
await rejects('terminal order cannot move back', s.as(ID.vendor, `select vendor_start_preparing($1)`, [o1]), /Illegal order transition/)
await rejects('admin cannot reopen PICKED_UP order', s.as(ID.admin, `select admin_cancel_order($1)`, [o1]), /Illegal order transition/)
await rejects('token cannot be replayed', s.as(ID.vendor, `select verify_pickup_token($1)`, [t]), /already used/)

console.log('\n== Online payment (Razorpay) state machine')
cart = await fillCart(s, ID.student, ID.outletA, [{ food: ID.food, qty: 1 }])
const stock1 = await inv(ID.food)
const on1 = (await s.as(ID.student, `select place_order($1,$2,'ONLINE') id`, [cart, slotA])).rows[0].id
eq('online order holds stock while unpaid', await inv(ID.food), stock1 - 1)
eq('vendor cannot see unpaid online order', (await s.as(ID.vendor, `select id from orders where id=$1`, [on1])).rows.length, 0)
cart = await fillCart(s, ID.student, ID.outletA, [{ food: ID.food, qty: 1 }])
await rejects('second online order while one awaits payment -> PAYMENT_IN_PROGRESS', s.as(ID.student, `select place_order($1,$2,'ONLINE')`, [cart, slotA]), new RegExp('PAYMENT_IN_PROGRESS:' + on1))
await rejects('another user cannot prepare my payment', s.service(`select crave_payment_prepare($1,$2)`, [on1, ID.student2]), /Order not found/)
const prep = (await s.service(`select crave_payment_prepare($1,$2) j`, [on1, ID.student])).rows[0].j
eq('payable amount comes from DB (₹105 -> 10500 paise)', prep.amount_paise, 10500)
eq('first attach wins', (await s.service(`select crave_payment_attach($1,'order_RZP1') r`, [on1])).rows[0].r, 'order_RZP1')
eq('second attach returns the existing id (no second Razorpay order)', (await s.service(`select crave_payment_attach($1,'order_RZP2') r`, [on1])).rows[0].r, 'order_RZP1')
eq('prepare now reuses razorpay order', (await s.service(`select crave_payment_prepare($1,$2) j`, [on1, ID.student])).rows[0].j.razorpay_order_id, 'order_RZP1')
await rejects('wrong amount rejected + logged', s.service(`select crave_payment_apply('order_RZP1','pay_1','PAID',99999)`), /amount mismatch/)
await rejects('someone else cannot confirm my payment', s.service(`select crave_payment_apply('order_RZP1','pay_1','PAID',10500,'sig',$1)`, [ID.student2]), /Order not found/)
await s.service(`select crave_payment_apply('order_RZP1','pay_fail','FAILED',10500)`)
eq('failed attempt keeps order retryable', (await one(`select status::text s, payment_status::text p from orders where id=$1`, [on1])), { s: 'PLACED', p: 'FAILED' })
const r1 = (await s.service(`select crave_payment_apply('order_RZP1','pay_1','PAID',10500,'sig') j`)).rows[0].j
eq('success marks PAID', [r1.payment_status, r1.changed], ['PAID', true])
const r2 = (await s.service(`select crave_payment_apply('order_RZP1','pay_1','PAID',10500,'sig') j`)).rows[0].j
eq('replayed verification is a no-op', [r2.payment_status, r2.changed], ['PAID', false])
await s.service(`select crave_payment_apply('order_RZP1','pay_fail2','FAILED',10500)`)
eq('late failure webhook cannot downgrade a paid order', (await one(`select payment_status::text p from orders where id=$1`, [on1])).p, 'PAID')
await s.service(`select crave_payment_apply('order_RZP1','pay_dup','PAID',10500)`)
eq('duplicate second payment keeps first id, audited', [(await one(`select razorpay_payment_id id from payments where order_id=$1`, [on1])).id, (await one(`select count(*)::int c from audit_logs where action='DUPLICATE_PAYMENT'`)).c], ['pay_1', 1])
eq('paid online order is now visible to vendor', (await s.as(ID.vendor, `select id from orders where id=$1`, [on1])).rows.length, 1)
await rejects('paid order cannot be cancelled by student', s.as(ID.student, `select cancel_my_order($1)`, [on1]), /Illegal order transition/)
await s.as(ID.vendor, `select vendor_accept_order($1)`, [on1]); log(true, 'vendor can accept a paid online order')
await s.as(ID.vendor, `select vendor_reject_order($1,'out of stock')`, [on1])
eq('rejecting paid order -> refund candidate listed for management', (await s.as(ID.admin, `select admin_refund_candidates() j`)).rows[0].j.map(x => x.razorpay_payment_id), ['pay_1'])
await s.service(`select crave_payment_mark_refunded($1,'rfnd_1')`, [on1]); eq('refund bookkeeping', (await one(`select payment_status::text p from orders where id=$1`, [on1])).p, 'REFUNDED')
eq('refunded order leaves refund list', (await s.as(ID.admin, `select admin_refund_candidates() j`)).rows[0].j.length, 0)

console.log('\n== Abandoned / cancelled online orders')
cart = await fillCart(s, ID.student, ID.outletA, [{ food: ID.food, qty: 3 }]); const stock2 = await inv(ID.food), bk2 = await booked(slotA)
const on2 = (await s.as(ID.student, `select place_order($1,$2,'ONLINE') id`, [cart, slotA])).rows[0].id
await s.as(ID.student, `select cancel_my_order($1,'Payment cancelled')`, [on2])
eq('user cancels checkout -> stock+slot restored, payment FAILED', [await inv(ID.food), await booked(slotA), (await one(`select status::text s from payments where order_id=$1`, [on2])).s], [stock2, bk2, 'FAILED'])
cart = await fillCart(s, ID.student, ID.outletA, [{ food: ID.food, qty: 2 }])
const on3 = (await s.as(ID.student, `select place_order($1,$2,'ONLINE') id`, [cart, slotA])).rows[0].id
await s.service(`select crave_payment_attach($1,'order_RZP3')`, [on3])
await db.query(`update orders set payment_expires_at = now() - interval '1 minute' where id=$1`, [on3])
eq('sweep expires abandoned order', (await s.service(`select crave_expire_unpaid_orders() n`)).rows[0].n, 1)
eq('expired order released stock + slot', [await inv(ID.food), await booked(slotA)], [stock2, bk2])
await rejects('cannot start payment on expired order', s.service(`select crave_payment_prepare($1,$2)`, [on3, ID.student]), /no longer be paid|expired/)
await s.service(`select crave_payment_apply('order_RZP3','pay_late','PAID')`)
eq('late success on expired order is surfaced for refund (not silently fulfilled)', [(await one(`select status::text s, payment_status::text p from orders where id=$1`, [on3])), (await s.as(ID.admin, `select admin_refund_candidates() j`)).rows[0].j.length], [{ s: 'CANCELLED', p: 'PAID' }, 1])
await rejects('vendor cannot cook a cancelled order', s.as(ID.vendor, `select vendor_accept_order($1)`, [on3]), /Illegal order transition/)

console.log('\n== Outlet reviews')
cart = await fillCart(s, ID.student, ID.outletA, [{ food: ID.food, qty: 1 }]); const op = (await s.as(ID.student, `select place_order($1,$2,'PAY_AT_COUNTER') id`, [cart, slotA])).rows[0].id
await rejects('cannot review before PICKED_UP', s.as(ID.student, `insert into outlet_reviews(outlet_id,order_id,student_id,rating) values ($1,$2,$3,5)`, [ID.outletA, op, ID.student]), /completed \(picked-up\)/)
for (const f of ['vendor_accept_order', 'vendor_start_preparing', 'vendor_mark_ready']) await s.as(ID.vendor, `select ${f}($1)`, [op])
await s.as(ID.vendor, `select verify_pickup_token((select token_value from pickup_tokens where order_id=$1))`, [op])
await rejects('rating 6 rejected', s.as(ID.student, `insert into outlet_reviews(outlet_id,order_id,student_id,rating) values ($1,$2,$3,6)`, [ID.outletA, op, ID.student]), /check/i)
await rejects('review text > 1000 chars rejected', s.as(ID.student, `insert into outlet_reviews(outlet_id,order_id,student_id,rating,review_text) values ($1,$2,$3,5,repeat('x',1001))`, [ID.outletA, op, ID.student]), /check/i)
await rejects('student2 cannot review student1 order', s.as(ID.student2, `insert into outlet_reviews(outlet_id,order_id,student_id,rating) values ($1,$2,$3,5)`, [ID.outletA, op, ID.student2]), /only review outlets you ordered/)
await rejects('cannot spoof student_id', s.as(ID.student2, `insert into outlet_reviews(outlet_id,order_id,student_id,rating) values ($1,$2,$3,5)`, [ID.outletA, op, ID.student]), /yourself|row-level/)
await rejects('wrong outlet for the order rejected', s.as(ID.student, `insert into outlet_reviews(outlet_id,order_id,student_id,rating) values ($1,$2,$3,5)`, [ID.outletB, op, ID.student]), /not placed at that outlet/)
const rv = (await s.as(ID.student, `insert into outlet_reviews(outlet_id,order_id,student_id,rating,review_text) values ($1,$2,$3,4,'  tasty  ') returning id, review_text`, [ID.outletA, op, ID.student])).rows[0]
eq('review stored, text trimmed', rv.review_text, 'tasty')
await rejects('one review per order', s.as(ID.student, `insert into outlet_reviews(outlet_id,order_id,student_id,rating) values ($1,$2,$3,5)`, [ID.outletA, op, ID.student]), /unique|duplicate/i)
eq('outlet rating synced from reviews', (await one(`select rating::float r, total_reviews t from outlets where id=$1`, [ID.outletA])), { r: 4, t: 1 })
await s.as(ID.student, `update outlet_reviews set rating=5, review_text='great' where id=$1`, [rv.id]); eq('student edits own review', (await one(`select rating::float r from outlets where id=$1`, [ID.outletA])).r, 5)
await rejects('student cannot hide/unhide own review', s.as(ID.student, `update outlet_reviews set is_visible=false where id=$1`, [rv.id]), /Only management/)
await rejects('student2 cannot edit it', s.as(ID.student2, `update outlet_reviews set rating=1 where id=$1`, [rv.id]).then(r => { if (!r.affectedRows) throw new Error('0 rows') }), /0 rows/)
await rejects('student2 cannot delete it', s.as(ID.student2, `delete from outlet_reviews where id=$1`, [rv.id]).then(r => { if (!r.affectedRows) throw new Error('0 rows') }), /0 rows/)
await s.as(ID.vendor, `insert into outlet_review_replies(review_id,vendor_id,reply_text) values ($1,$2,'thanks!')`, [rv.id, ID.vendor]); log(true, 'owning vendor can reply')
await rejects('other vendor cannot reply', s.as(ID.vendor2, `insert into outlet_review_replies(review_id,vendor_id,reply_text) values ($1,$2,'hax')`, [rv.id, ID.vendor2]), /row-level security/)
await rejects('student cannot reply', s.as(ID.student, `insert into outlet_review_replies(review_id,vendor_id,reply_text) values ($1,$2,'self')`, [rv.id, ID.student]), /row-level security/)
await rejects('vendor reply cannot be empty', s.as(ID.vendor, `update outlet_review_replies set reply_text='   ' where review_id=$1`, [rv.id]), /check/i)
eq('student sees reply via RPC', (await s.as(ID.student2, `select get_outlet_reviews($1) j`, [ID.outletA])).rows[0].j.reviews[0].reply.reply_text, 'thanks!')
eq('RPC exposes first name only', (await s.as(ID.student2, `select get_outlet_reviews($1) j`, [ID.outletA])).rows[0].j.reviews[0].reviewer_name, 'Stu')
await s.as(ID.vendor, `update outlet_review_replies set reply_text='updated' where review_id=$1`, [rv.id]); log(true, 'vendor edits reply')
await rejects('non-admin cannot moderate', s.as(ID.vendor, `select admin_set_outlet_review_visibility($1,false)`, [rv.id]), /ADMIN/)
await s.as(ID.admin, `select admin_set_outlet_review_visibility($1,false)`, [rv.id])
eq('hidden review absent from student RPC', (await s.as(ID.student2, `select get_outlet_reviews($1) j`, [ID.outletA])).rows[0].j.total, 0)
eq('hidden review absent from vendor RPC', (await s.as(ID.vendor, `select get_vendor_outlet_reviews() j`)).rows[0].j.total, 0)
eq('hidden review not selectable by vendor', (await s.as(ID.vendor, `select id from outlet_reviews`)).rows.length, 0)
eq('hidden review absent from reply listing for vendor', (await s.as(ID.vendor, `select id from outlet_review_replies`)).rows.length, 0)
await rejects('vendor cannot reply to a hidden review', s.as(ID.vendor, `insert into outlet_review_replies(review_id,vendor_id,reply_text) values ($1,$2,'x')`, [rv.id, ID.vendor]), /row-level security|unique/)
eq('management still sees hidden review', (await s.as(ID.admin, `select admin_search_outlet_reviews(null,'hidden') j`)).rows[0].j.total, 1)
eq('outlet rating recomputed without hidden review', (await one(`select rating::float r, total_reviews t from outlets where id=$1`, [ID.outletA])), { r: 0, t: 0 })
await s.as(ID.admin, `select admin_set_outlet_review_visibility($1,true)`, [rv.id]); eq('unhide restores visibility', (await s.as(ID.student2, `select get_outlet_reviews($1) j`, [ID.outletA])).rows[0].j.total, 1)
eq('search by text', (await s.as(ID.admin, `select admin_search_outlet_reviews('GREAT') j`)).rows[0].j.total, 1)
await rejects('vendor B RPC shows none of A\'s reviews', s.as(ID.vendor2, `select get_vendor_outlet_reviews() j`).then(r => { if (r.rows[0].j.total !== 0) throw new Error('leak'); throw new Error('ok-empty') }), /ok-empty/)
await s.as(ID.student, `delete from outlet_reviews where id=$1`, [rv.id]); log(true, 'student deletes own review (reply cascades)')

console.log('\n== Food reviews (existing live tables)')
const oi = (await one(`select id from order_items where order_id=$1 limit 1`, [op])).id
const fr = (await s.as(ID.student, `insert into reviews(student_id,food_item_id,order_id,order_item_id,rating,review_text) values ($1,$2,$3,$4,5,'yum') returning id`, [ID.student, ID.food, op, oi])).rows[0].id
await rejects('student cannot hide own food review', s.as(ID.student, `update reviews set is_visible=false where id=$1`, [fr]), /Only management/)
await rejects('food review > 1000 chars rejected', s.as(ID.student, `update reviews set review_text=repeat('x',1001) where id=$1`, [fr]), /1000/)
await rejects('vendor of other outlet cannot reply to food review', s.as(ID.vendor2, `insert into review_replies(review_id,vendor_id,reply_text) values ($1,$2,'hax')`, [fr, ID.vendor2]), /own food/)
await s.as(ID.vendor, `insert into review_replies(review_id,vendor_id,reply_text) values ($1,$2,'thank you')`, [fr, ID.vendor]); log(true, 'owner vendor replies to food review')
await rejects('vendor cannot spoof vendor_id on reply (overwritten)', s.as(ID.vendor2, `update review_replies set reply_text='x' where review_id=$1`, [fr]).then(r => { if (!r.affectedRows) throw new Error('0 rows') }), /0 rows/)
await s.as(ID.admin, `select admin_set_food_review_visibility($1,false)`, [fr])
eq('management can hide food review', (await one(`select is_visible v from reviews where id=$1`, [fr])).v, false)
eq('management food review search sees hidden', (await s.as(ID.admin, `select admin_search_food_reviews(null,'hidden') j`)).rows[0].j.total, 1)

console.log('\n== Dashboards / analytics (revenue = PAID/CAPTURED only)')
const dash = (await s.as(ID.admin, `select get_management_dashboard(7) j`)).rows[0].j
const expectRev = Number((await one(`select coalesce(sum(amount),0)::float s from payments where status::text in ('PAID','CAPTURED')`)).s)
eq('paidRevenue equals sum of PAID payments only', dash.paidRevenue, expectRev)
eq('razorpay + cash = paid', dash.razorpayRevenue + dash.cashRevenue, dash.paidRevenue)
eq('trend has 7 daily buckets', dash.trend.length, 7)
log(dash.refundRequiredCount === 1, 'refundRequired counts paid-but-cancelled orders', JSON.stringify([dash.refundRequiredCount]))
const vd = (await s.as(ID.vendor, `select get_vendor_dashboard() j`)).rows[0].j
eq('vendor with 2 outlets sees both', vd.outlets.map(o => o.name).sort(), ['Outlet A', 'Outlet A2'])
eq('vendor B dashboard has only own outlet', (await s.as(ID.vendor2, `select get_vendor_dashboard() j`)).rows[0].j.outlets.map(o => o.name), ['Outlet B'])
await rejects('vendor cannot read other vendor outlet dashboard', s.as(ID.vendor2, `select get_vendor_dashboard($1)`, [ID.outletA]), /Outlet not found/)
await rejects('student cannot call vendor dashboard', s.as(ID.student, `select get_vendor_dashboard()`), /Only vendors/)

console.log('\n== Catalogue guards')
await rejects('vendor cannot forge outlet rating', s.as(ID.vendor, `update outlets set rating=5 where id=$1`, [ID.outletA]), /managed by Crave/)
await rejects('vendor cannot hand outlet to someone else', s.as(ID.vendor, `update outlets set vendor_id=$2 where id=$1`, [ID.outletA, ID.vendor2]), /managed by Crave/)
await rejects('vendor cannot forge food rating', s.as(ID.vendor, `update food_items set rating=5 where id=$1`, [ID.food]), /computed from reviews/)
await s.as(ID.vendor, `update food_items set is_available=false where id=$1`, [ID.food]); log(true, 'vendor can still toggle availability'); await db.query(`update food_items set is_available=true where id=$1`, [ID.food])
await rejects('vendor cannot edit other vendor food', s.as(ID.vendor, `update food_items set price=1 where id=$1`, [ID.foodB]).then(r => { if (!r.affectedRows) throw new Error('0 rows') }), /0 rows/)
await db.query(`update food_items set is_available=false where id=$1`, [ID.foodB])
eq('vendor search does not leak other vendor\'s unavailable food', (await s.as(ID.vendor, `select search_food('', null, null, null, null, false) j`)).rows[0].j.map(x => x.name).sort(), ['Biryani', 'Dosa'])
eq('student search hides unavailable food', (await s.as(ID.student, `select search_food('', null, null, null, null, false) j`)).rows[0].j.map(x => x.name).sort(), ['Biryani', 'Dosa'])
eq('owner of unavailable item still sees it', (await s.as(ID.vendor2, `select search_food('', null, null, null, null, false) j`)).rows[0].j.map(x => x.name).sort(), ['Biryani', 'Dosa', 'Pizza'])

console.log(`\n${pass} passed, ${fail} failed`)
process.exit(fail ? 1 : 0)
